site_name: Vault Quickstart
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    primary: blue grey
repo_url: https://github.com/eformat/vault-quickstart
repo_name: eformat/vault-quickstart
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eformat
    - icon: fontawesome/brands/github
      link: https://github.com/eformat
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/eformat
markdown_extensions:
  - attr_list
  - md_in_html
plugins:
  - git-revision-date
nav:
  - index.md
  - 1-vault-install.md
  - 2-vault-configuration.md
  - 3-application.md
  - 4-external-secrets-operator.md
  - 5-vault-configuration-operator.md
